# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "containerst"
    key                  = "./terraform.tfstate"
    resource_group_name  = "1-4ad89eca-playground-sandbox"
    snapshot             = true
    storage_account_name = "storeelonetwork"
    subscription_id      = "2213e8b1-dbc7-4d54-8aff-b5e315df5e5b"
    tenant_id            = "84f1e4ea-8554-43e1-8709-f0b8589ea118"
  }
}
