# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
        key = "./terraform.tfstate"
        resource_group_name = "1-af5835bd-playground-sandbox"
        storage_account_name = "pseudo0021"
        container_name = "hub"
  }
}
